# overlays/dev/patch-athena-sa.yaml
# base의 role-arn placeholder를 dev 클러스터 실제 IAM Role ARN으로 덮어씀.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: athena-batch-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::834922934330:role/snipy-dev-cluster-athena-cronjob-role"