apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: management-service-secrets
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: management-service-secrets
  data:
    - secretKey: DB_APP_PASSWORD
      remoteRef:
        key: snipy-cluster/rds/app-user-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: snipy-cluster/app/jwt-secret
    - secretKey: KAKAO_CLIENT_ID
      remoteRef:
        key: snipy-cluster/app/kakao-client-id
    - secretKey: KAKAO_CLIENT_SECRET
      remoteRef:
        key: snipy-cluster/app/kakao-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redirect-service-secrets
spec:
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: redirect-service-secrets
  data:
    - secretKey: DB_APP_PASSWORD
      remoteRef:
        key: snipy-cluster/rds/app-user-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: snipy-cluster/app/jwt-secret